name: Static Website Deployment

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # Change this if your default branch is different

# Define the job that runs the deployment
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      # Step 3: Install dependencies (if necessary, for example, if you have build steps)
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # The directory to publish, here it is the root of your repository
