name: Deploy Website to GitHub Pages

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

# Define the jobs to be run
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (even though it's a static site, it's needed for npm-related actions)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install GitHub Pages dependency to push the site
      - name: Install GitHub Pages
        run: npm install -g gh-pages

      # Step 4: Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          gh-pages -d .  # Deploy the current directory

